### ISSUE TITLE
install of Ethereum version fails on requests[security]

### ISSUE THREAD

**Issue by guix77** [blockchain-certificates/cert-issuer#103]
Hi,

When running python setup.py experimental --blockchain=ethereum I'm stuck here, any idea ?

```
Installing collected packages: idna, urllib3, chardet, certifi, six, pycparser, cffi, enum34, asn1crypto, ipaddress, cryptography, pyOpenSSL, requests
Traceback (most recent call last):
  File "setup.py", line 70, in <module>
    packages=find_packages()
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 44, in run
    install(reqs)
  File "setup.py", line 48, in install
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', package])
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', 'install', 'requests[security]>=2.18.4\n']' returned non-zero exit status -11
```

If of any help, running python -m requests.help gives me:

```
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": "2.2.2"
  }, 
  "idna": {
    "version": "2.7"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.13"
  }, 
  "platform": {
    "release": "4.9.0-6-amd64", 
    "system": "Linux"
  }, 
  "pyOpenSSL": {
    "openssl_version": "1010008f", 
    "version": "18.0.0"
  }, 
  "requests": {
    "version": "2.19.1"
  }, 
  "system_ssl": {
    "version": "1010006f"
  }, 
  "urllib3": {
    "version": "1.23"
  }, 
  "using_pyopenssl": true
}
```

**Comment by AnthonyRonning** [comment]
Not seeing an issue in the docker image, so that implies that there's not a recent package dependency problem overall. 

Try python3? I also see `returned non-zero exit status -11` so maybe getting to the bottom of that might help?

**Comment by guix77** [comment]
Ah, I didn't try the Docker image, I thought it was Bitcoin only.

Python3 does not help, I have the same problem. But I fixed it using virtualenv like described here : https://github.com/datts68/cert-issuer/blob/7de136f7c1321e3a4b77a18451f2e1ba293d3ac4/docs/deploy_cert_issuer_on_ubuntu.md

**Comment by AnthonyRonning** [comment]
Great! It sets up for bitcoin by default, so you'll have to run that experimental --blockchain=ethereum command, edit the conf.ini and you'll have it set up for ethereum. 

When you're logged into the docker image:
```
cd cert-issuer
python3 setup.py experimental --blockchain=ethereum
cd ../
```

**Comment by guix77** [comment]
Thanks :)

I might try the Docker another time, it seems I'm getting close to it in an install with Ansible.

**Comment by EthanSamray** [comment]
try "sudo" 
sudo python3 setup.py experimental --blockchain=ethereum
