### ISSUE TITLE
Add exceptions to etherscan errors

### ISSUE THREAD

**Issue by AnthonyRonning** [blockchain-certificates/cert-issuer#104]
Our ethereum connector code throws an error if the response status code is not 200. 

Unfortunately, etherscan gives a 200 back even if there's an error on there end. The following is an example of an error being returned back from etherscan:

```
{‘jsonrpc’: ‘2.0’, ‘error’: {‘code’: -32010, ‘message’: ‘Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 500000000000000 and got: 0.’}, ‘id’: 1}
```

Would be nice if we could throw and return the message. Otherwise, a `INFO - Transaction ID obtained from broadcast through Etherscan: None` gets returned. 

Some discussion on that here: https://community.blockcerts.org/t/no-transaction-occuring/1142

**Comment by akodate** [comment]
Hi, I've added handling for errors from Etherscan as you proposed.
Let me know if the PR looks good to you.

**Comment by AnthonyRonning** [comment]
Thanks! Merged.
