### ISSUE TITLE
GDPR regulations

### ISSUE THREAD

**Issue by Dakshan07** [blockchain-certificates/cert-issuer#108]
Hi, I am a student doing my thesis from TU Delft. I came acros blockerts via the article in medium and I found it very interesting. I have a question though, with the GDPR regulations in Europe you cannot store personal information on the chain, how did you manage to negate it or is that currently not your domain or research.

**Comment by sijpkes** [comment]
That’s a good question. I’d be interested in the answer too. I think the GDPR is a good precedent that others will be following in the coming years.

**Comment by Dakshan07** [comment]
True,one of the pitfalls is that even pseudo anonymized data is still considered private data and immutability which is touted as an asset in blockchain is also a bane as far is GDPR is concerned.

**Comment by sijpkes** [comment]
@daniel-jozsef I'm interested in knowing more about this.  What's a good primer on Merkle for a non-encryption minded person?

**Comment by daniel-jozsef** [comment]
@sijpkes https://en.wikipedia.org/wiki/Merkle_tree

**Comment by AnthonyRonning** [comment]
Yes, @daniel-jozsef is correct. No personal data is stored, only hashes. And blockcerts supports having nonces in the certificate as well, thus making guesses even more infeasible.

**Comment by daniel-jozsef** [comment]
Do note though that nonces are important. Unsalted hashes of personal data qualify as personal data under the GDPR, based on an EU guideline. I can't find the link but I'll update with it when I have it.
