### ISSUE TITLE
Blockcerts implementation in EOS

### ISSUE THREAD

**Issue by blockchain-expert** [blockchain-certificates/cert-issuer#111]
Why can't we implement blockcerts in EOS? Transactions in EOS are almost free and thus a better candidate for storing certificates in blockchain.

**Comment by AnthonyRonning** [comment]
> Why can't we implement blockcerts in EOS? 

Nothing stopping you at all! Blockcerts is blockchain agnostic, so as long as the interfaces are in place throughout the ecosystem of apps (cert-issuers, cert-verifiers, etc) to communicate with EOS then blockcerts should work with it.
