### ISSUE TITLE
How to reduce the transaction fee from 60000 satoshis

### ISSUE THREAD

**Issue by ktrev** [blockchain-certificates/cert-issuer#118]
We would like to make it 6000 satoshis
We tried adding tx_fee = 0.00006 in the conf.ini. But it didn't work
Any suggestions?

**Comment by danishfastian** [comment]
0.0006 is the minimum fees check the below thread on some suggestion to change it from code. Let me know if it work for you
https://community.blockcerts.org/t/lowering-transaction-fee-in-blockcert/1005

**Comment by stuartf** [comment]
According to this post: https://community.blockcerts.org/t/how-to-reduce-the-bitcoin-transaction-fee-in-cert-issuer-from-60000-satoshis-to-6000/1517

The max of `tx_fee` (.0006) and `satoshi_per_byte * bytes` (250 * ~24) is the fee that gets used. So, try setting `satoshi_per_byte=25` along with `tx_fee=.00006` in your conf.ini.

**Comment by AnthonyRonning** [comment]
Sorry we didn't get around to answering. Yes, @stuartf is correctly. the max is used there. Let us know if there's a problem with that.
