### ISSUE TITLE
Feature Request: QR Code on Certificates

### ISSUE THREAD

**Issue by vivekkiran** [blockchain-certificates/cert-issuer#128]
It would be nice if QR Code can be displayed on the certificate, so that it can be easily scanned and added into mobile wallet similar to https://www.uport.me/ .

**Comment by AnthonyRonning** [comment]
Good suggestion, and good use case for sure. At this moment though, it's best that it's done on the issuers' side. 

Issuers create the visual displays right now via the `display_html` variable on each certificate. To allow issuers to continue to have control over what each cert looks like, it's a good idea for them to fine tune what, where, and how the qr code looks. Some might want it small in a corner, some at the top, some in the middle of the page, etc. All of that is within full creative control of the issuer, so having something automatically do so might ruin the experience of what certificates look like. 

On the issuer side, generate a QR code based on the expected URL of the certificate, more than likely based on the `id` of the certificate which should be the URL anyways. I forget how we did QR codes and automatic import, but at Learning Machine, our QR codes on certificates will actually auto add to the recipient's wallet when scanned from a mobile phone with the blockcerts app installed.
