### ISSUE TITLE
 issue_certificates.py missing

### ISSUE THREAD

**Issue by vivekkiran** [blockchain-certificates/cert-issuer#129]
I am unable to find issue_certificates.py mentioned in the documentation, I have followed all the steps in the documentation, another question I have is is it possible to run it without setting up whole bitcoin/ethereum node as it requires at least 100GB of space.

**Comment by yancyribbens** [comment]
This looks like a typo in the documentation.  To issue the certificates, run: `python cert-issuer -c conf.ini`:

**Comment by yancyribbens** [comment]
Here's a PR to clarify https://github.com/blockchain-certificates/cert-issuer/pull/134
