### ISSUE TITLE
Berkeley DB?

### ISSUE THREAD

**Issue by vivekkiran** [blockchain-certificates/cert-issuer#130]
https://github.com/blockchain-certificates/cert-issuer/blob/2a663fcce5eaf9cac13aefdac427f4cc27e812d7/Dockerfile.web#L11

Is Berkeley DB being used in the project anywhere? I see that it has been mentioned in the docker file.

**Comment by yancyribbens** [comment]
Yes, the Berkley Database is used by `bitcoind`
