### ISSUE TITLE
Installation fails due to conflicting pysha3 version

### ISSUE THREAD

**Issue by NeolithEra** [blockchain-certificates/cert-issuer#145]
Hi, users are unable to run **_cert-issuer_** due to dependency conflict with _**pysha3**_ package. 

As shown in the following full dependency graph of **_cert-issuer_**, **_cert-issuer_** requires _**pysha3>=1.0.2**_，while **_chainpoint>=0.0.2_** requires _**pysha3==1.0b1**_.

According to pip’s “first found wins” installation strategy, _**pysha3==1.0.2**_ is the actually installed version. 
However, _**pysha3==1.0.2**_ does not satisfy _**pysha3==1.0b1**_.

### Dependency tree-----
```
cert-issuer(version range:)
| +-cert-core(version range:>=2.1.9)
| | +-requests(version range:>=2.18.4)
| | +-cert-schema(version range:>=2.1.5)
| | | +-pyld(version range:>=1.0.3)
| | | +-jsonschema(version range:>=2.6.0)
| | | +-requests(version range:>=2.18.4)
| | | +-tox(version range:>=3.0.0)
| | | +-validators(version range:>=0.12.1)
| | | | +-six(version range:>=1.4.0)
| | | | +-decorator(version range:>=3.4.0)
| | +-configargparse(version range:>=0.12.0)
| | +-connexion(version range:>=1.1.14)
| | +-enum34(version range:>=1.1.6python)
| | +-Flask-PyMongo(version range:>=0.5.1)
| | +-jsonschema(version range:>=2.6.0)
| | +-python-dateutil(version range:>=2.6.1)
| | +-pytz(version range:>=2017.2)
| | +-simplekv(version range:>=0.10.0)
| | +-tox(version range:>=3.0.0)
| | +-validators(version range:>=0.12.1)
| | | +-six(version range:>=1.4.0)
| | | +-decorator(version range:>=3.4.0)
| +-cert-schema(version range:>=2.1.5)
| | +-pyld(version range:>=1.0.3)
| | +-jsonschema(version range:>=2.6.0)
| | +-requests(version range:>=2.18.4)
| | +-tox(version range:>=3.0.0)
| | +-validators(version range:>=0.12.1)
| | | +-six(version range:>=1.4.0)
| | | +-decorator(version range:>=3.4.0)
| +-chainpoint(version range:>=0.0.2)
| | +-merkletools(version range:==1.0.2)
| | | +-pysha3(version range:==1.0b1)
| +-coincurve(version range:==7.1.0)
| +-configargparse(version range:==0.12.0)
| +-ethereum(version range:==2.3.1)
| +-glob2(version range:==0.6)
| +-jsonschema(version range:<3.0.0)
| +-mock(version range:==2.0.0)
| +-pycoin(version range:==0.80)
| +-pyld(version range:>=1.0.3)
| +-pysha3(version range:>=1.0.2)
| +-python-bitcoinlib(version range:>=0.10.1)
| +-requests(version range:>=2.18.4)
| +-rlp(version range:<1)
| +-tox(version range:>=3.0.0)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
# Solution
Fix your direct dependency to be pysha3==1.0b1. I have checked this revision will not affect your downstream projects now.


@AnthonyRonning  Could you help me review this issue? I can submit a PR to fix it.

**Comment by AnthonyRonning** [comment]
Thanks @NeolithEra, there's been a couple comments on that on our forums: https://community.blockcerts.org/t/merkletools-dependences-pysha3/649/3

I forgot why we didn't/couldn't set to `pysha3==1.0b1`, if any reason, but we've got this docker script happening to avoid the problem when running from docker: 

```
sed -i.bak s/==1\.0b1/\>=1\.0\.2/g /usr/lib/python3.*/site-packages/merkletools-1.0.2-py3.*.egg-info/requires.txt
```

Definitely not ideal though.

**Comment by AnthonyRonning** [comment]
Okay I remember why it wouldn't work. `1.0b` has incompatibilities with python3.6. 

```
/Users/anthonyronning/Dev/Repos/Personal/cert-issuer/venv/lib/python3.7/site-packages/merkletools-1.0.2-py3.7.egg/merkletools/__init__.py:7: UserWarning: sha3 is not working!
  warn("sha3 is not working!")
```

Per https://github.com/tiran/pysha3 - 
### pysha3 1.0.2

*Release: 05-Feb-2017*

-   Rename internal C extension to \_pysha3 to avoild conflict with
    Python 3.6' \_sha3 extension.

--- 
I got that warning, but after awhile the certificates did get generated and all seems correct but I do not like that warning. Until https://github.com/lontivero/PyChainpoint/issues/2 gets resolved, going to have to live with manually/programmatically changing the merkletools requires.txt. The alternative is for us to maintain our own version of merkletools pointing to the more recent version of pysha3.

**Comment by AnthonyRonning** [comment]
Just saw that the issue is already being tracked here: https://github.com/blockchain-certificates/cert-issuer/issues/102
