### ISSUE TITLE
No module named setup tools

### ISSUE THREAD

**Issue by Skyquek** [blockchain-certificates/cert-issuer#146]
No module named setup tools error when running "python setup.py install" in docker

Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import find_packages
ImportError: No module named setuptools

**Comment by AnthonyRonning** [comment]
Are you running from a virtual environment? 

https://github.com/blockchain-certificates/cert-issuer/blob/master/docs/virtualenv.md

**Comment by AnthonyRonning** [comment]
I reproduced this issue when I was not set up with a venv correctly, and verified that by running the instructions in the docs, it worked. Closing.
