### ISSUE TITLE
Add another Ethereum API

### ISSUE THREAD

**Issue by AnthonyRonning** [blockchain-certificates/cert-issuer#152]
This one looks like a good one: https://www.myetherapi.com/

There's also a Blockcypher one: https://www.blockcypher.com/dev/ethereum/#introduction

Should be added here: https://github.com/blockchain-certificates/cert-issuer/blob/master/cert_issuer/blockchain_handlers/ethereum/connectors.py

**Comment by AnthonyRonning** [comment]
Etherscan's ropsten api is getting reports of cloudflare getting in the way. Confirmed this myself. Mainnet does not seem affected. 

https://community.blockcerts.org/t/cert-issuer-errors-insufficientfundserror/2122/2

https://community.blockcerts.org/t/access-denied-ethereum-ropsten/2107

**Comment by AnthonyRonning** [comment]
Added myetherwallet for ethereum mainnet and ethereum ropsten. May still be benefitial to have Blockcypher as well, but at least we have 2 now 😄

**Comment by officialasit** [comment]
> 
> 
> Etherscan's ropsten api is getting reports of cloudflare getting in the way. Confirmed this myself. Mainnet does not seem affected.
> 
> https://community.blockcerts.org/t/cert-issuer-errors-insufficientfundserror/2122/2
> 
> https://community.blockcerts.org/t/access-denied-ethereum-ropsten/2107

Hi @AnthonyRonning 

Any solution for this? Cloudflare is getting in the way of the Ropsten API.
Thanks

**Comment by lemoustachiste** [comment]
I @officialasit, which version are you using and which provider is failing?

**Comment by lemoustachiste** [comment]
Fixed by https://github.com/blockchain-certificates/cert-issuer/blob/eeb2c1d7c6b90eb9f09763ee84479b2fe447c0cc/cert_issuer/blockchain_handlers/ethereum/connectors.py#L161
