### ISSUE TITLE
Hello New to BlockCert

### ISSUE THREAD

**Issue by turrenk** [blockchain-certificates/cert-issuer#159]
Hello Community,

Looking to get my feet wet with Block Cert. I have installed the cert-verifier, and tools, but I cannot install the issuer. My windows 10 is not Pro, thus the Docker installation isn't going to work for me. Can I do this without DOCKER. I have seen another post that mentions setting up a virtenv and circumventing those steps. Can someone elaborate on this a little more, I'm not a complete novice but I've just recently begun delving deeper into python.  Thanks for your time and consideration.

**Comment by AnthonyRonning** [comment]
Hello @turrenk, welcome to the community. 

You can definitely run it without docker, and I highly suggest virtualenv. 

You can find the virtualenv instructions here: https://github.com/blockchain-certificates/cert-issuer/blob/master/docs/virtualenv.md

Then run through the prereqs: https://github.com/blockchain-certificates/cert-issuer#prerequisites

Set up your configs: https://github.com/blockchain-certificates/cert-issuer#configuring-cert-issuer

And lastly run the program with python: https://github.com/blockchain-certificates/cert-issuer#issuing

Any problems with those and I'd be happy to help. The community is also active on community.blockcerts.org too, some common errors can be found there. If the above works for you, feel free to close this issue 🙂
