### ISSUE TITLE
How can I access web resources without docker

### ISSUE THREAD

**Issue by AtulCIS** [blockchain-certificates/cert-issuer#162]
Hi,
I am new to cert-issuer and I have set up it from docker as well as from pip so both installation approaches worked for me but I am preferring without docker approach, so I want to use cert-issuer for my project and I want to access it using web services, I have checked your doc for HTTP Docker setup but I am curious is there any way to create web services for PIP installation?

**Comment by AnthonyRonning** [comment]
I'm not terribly familiar with the web services here, but maybe check out what the docker web portion is doing and replicate that on your local machine? 

https://github.com/blockchain-certificates/cert-issuer/blob/master/Dockerfile.web#L52
