### ISSUE TITLE
Add support for Binance Smart Chain for cheaper issuance of certificates

### ISSUE THREAD

**Issue by CreepyGizmo** [blockchain-certificates/cert-issuer#183]
Binance smart chain is compatible with Ethereum, it would be very simple to add support for Binance Smart Chain. 
https://docs.binance.org/smart-chain/developer/rpc.html

It should be very quick to add support, almost as simple as changing the infura url

**Comment by lemoustachiste** [comment]
You are welcome to open PRs for support of other blockchains, but keep in mind that we need to have support on the verification side too.
