### ISSUE TITLE
Insufficient Bitcoin Testnet Funds (When there are)

### ISSUE THREAD

**Issue by sofiawong-wz** [blockchain-certificates/cert-issuer#190]
Hi

![image](https://user-images.githubusercontent.com/68325331/103058208-97fd1780-45dc-11eb-9cf7-c711d4ffc4f3.png)

I am pretty sure there are enough funds. I have posted on forum and it seems that there is another user facing the same issue.

**Comment by sofiawong** [comment]
Issue is resolved.

**Comment by sofiawong-wz** [comment]
Issue is solved.
