### ISSUE TITLE
Ropsten etherscan API url changed

### ISSUE THREAD

**Issue by antonellopasella** [blockchain-certificates/cert-issuer#206]
The endpoint for wetherscan is no longer ropsten.etherscan.com but api-ropsten.etherscan.com

**Comment by lemoustachiste** [comment]
Hi @antonellopasella,

thanks for pointing this out. Do you mind opening a PR to update? Or at least provide some documentation/link about that change? Thanks

That could explain https://github.com/blockchain-certificates/cert-issuer/issues/205 
cc @h20190902

**Comment by antonellopasella** [comment]
it seems that all ropsen.etherscan occourrence should be renamed api-ropsten
I'm trying to create a working PR

ps: mainnet seems to work fine

**Comment by antonellopasella** [comment]
Hi @lemoustachiste I have a working solution for some problems I found in a fresh solution.
I note them here for discussion and we can agree how to move forward for PRs

Problems found:
1) Version conflicts 
 - see https://github.com/blockchain-certificates/cert-issuer/issues/207
2) Error when ethereum_rpc_url is None
 - in connectors.py it's only checked if hasattr(app_config, 'ethereum_rpc_url')
3) Error with ropsten etherscan API
 - API URL changed from ropsten.etherscan.io to api-ropsten.etherscan.io
 - default python request's user agent header is blocked by etherscan (403 error in console, 200 when opening in browser)

What would be the best way to share my fixes? One single PR or did you prefer 3 PRs instead?

Thanks!

**Comment by antonellopasella** [comment]
PR in https://github.com/blockchain-certificates/cert-issuer/pull/212

**Comment by antonellopasella** [comment]
Hi @lemoustachiste , any news about this PR?

**Comment by lemoustachiste** [comment]
merged
