### ISSUE TITLE
Fresh build, conflicts with dependencies

### ISSUE THREAD

**Issue by antonellopasella** [blockchain-certificates/cert-issuer#207]
Hi all, I cloned the repo and after a build , I got this errors

#6 55.51 INFO: pip is looking at multiple versions of cert-issuer to determine which version is compatible with other requirements. This could take a while.
#6 55.51 
#6 55.51 The conflict is caused by:
#6 55.51     cert-issuer 2.0.28 depends on pysha3>=1.0.2
#6 55.51     merkletools 1.0.2 depends on pysha3==1.0b1

I solved adding this lines to the Dockerfile and it seems working.

ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1
RUN pip3 install merkletools==1.0.2 \
    && pip3 install pysha3==1.0.2 \
    && sed -i.bak s/==1\.0b1/\>=1\.0\.2/g /usr/lib/python3.*/site-packages/merkletools-1.0.2-py3.*.egg-info/requires.txt

Can anyone confirm? Can I send a PR?

**Comment by lparkerlm** [comment]
Hi, I am working on a fix for this.  It seems there's been some drift in the dependencies, so I'm attempting to bring them up to date.

**Comment by antonellopasella** [comment]
This is my working Dockerfile.
It seems that adding multiple packages (with different dependencies) in a single line does'nt work.
I split them in multiple RUN and redo some of them afrer installing and setup.py



```
RUN apk add --update \
        bash \
        ca-certificates \
        curl \
        gcc \
        gmp-dev \
        libffi-dev \
        libressl-dev \
        linux-headers \
        make \
        musl-dev \
        python \
        python3 \
        python3-dev \
        tar
RUN apk add libxslt-dev
RUN apk add py-lxml
RUN python3 -m ensurepip \
    && pip3 install --upgrade pip setuptools

RUN pip3 install merkletools==1.0.2 \
    && pip3 install pysha3==1.0.2 \
    && sed -i.bak s/==1\.0b1/\>=1\.0\.2/g /usr/lib/python3.*/site-packages/merkletools-1.0.2-py3.*.egg-info/requires.txt

RUN pip3 install /cert-issuer/.



RUN pip3 install wheel
# install cert-issuer
RUN cd /cert-issuer && python3 setup.py experimental --blockchain=ethereum

RUN pip3 install web3==5.11.0
RUN pip3 install rlp==0.6.0
RUN pip3 install jsonschema==2.6.0

```

**Comment by lparkerlm** [comment]
It looks like we're thinking along the same lines.  I had to be a little more cautious with some of the package versions, due to compatibility issues elsewhere, but it's roughly the same.

I just merged a PR (https://github.com/blockchain-certificates/cert-issuer/pull/208) that should take care of it.  Thanks for the heads up :)
