### ISSUE TITLE
Ability to fetch gas price dynamically when issuing to the Ethereum Blockchain

### ISSUE THREAD

**Issue by abhisheksarka** [blockchain-certificates/cert-issuer#285]
Currently, we issue credentials using the cert issuer API. The gas price for every transaction is a fixed constant. A fixed gas price does not always help since we might be paying more for the transaction and we will have to keep a track of the fluctuations in the market.

The configuration available today is 
```python
--gas_price=20000000000
```

Proposed changes
```python
# requires --etherscan_api_token
--gas_price_dynamic=True
```

If this is something that could be useful, I am happy to open a PR for this.

**Comment by lemoustachiste** [comment]
Hi @abhisheksarka,

I'm not too experienced with the issue at stake, but I think your proposal is sensible so please go ahead and proceed with the PR.

**Comment by lparkerlm** [comment]
Also interested to see what you have in mind here!

**Comment by abhisheksarka** [comment]
I've opened a draft PR to get your initial impressions before I proceed with writing tests and fully verifying the functionality.
