### ISSUE TITLE
Missing argument for CertificateV3Handler constructor

### ISSUE THREAD

**Issue by san-esc** [blockchain-certificates/cert-issuer#286]
There is a missing argument on line 64 of file `/cert_issuer/blockchain_handlers/ethereum/__init__.py` that makes issuing with ethereum fails with the following error:

`TypeError: CertificateV3Handler.__init__() missing 1 required positional argument: 'app_config'`

**Comment by HarukiKondo** [comment]
I have a same error.

**Comment by HarukiKondo** [comment]
https://community.blockcerts.org/t/cert-issuer-c-conf-ini-error/3450/5

**Comment by HarukiKondo** [comment]
I found solution of this problem!!

**Comment by lemoustachiste** [comment]
Thanks all for your contribution and support
