### ISSUE TITLE
certificate not being able to be issued

### ISSUE THREAD

**Issue by shivam3192** [blockchain-certificates/cert-issuer#41]
when i am executing the command :
cert-issuer -c /etc/cert-issuer/conf.ini

I am getting following errors:

WARNING:root:Your app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
INFO:root:Processing 0 certificates
INFO - Processing 0 certificates
INFO:root:Processing 0 certificates under work path=/etc/cert-issuer/work
INFO - Processing 0 certificates under work path=/etc/cert-issuer/work
INFO:root:Signing certificates...
INFO - Signing certificates...
INFO:root:Set cost constants to recommended_tx_fee=0.000600,min_per_output=0.000028,satoshi_per_byte=250
INFO - Set cost constants to recommended_tx_fee=0.000600,min_per_output=0.000028,satoshi_per_byte=250
INFO:root:Total cost will be 84250 satoshis
INFO - Total cost will be 84250 satoshis
INFO:root:Preparing certificate batch
INFO - Preparing certificate batch
INFO:root:Signing certificates
INFO - Signing certificates
INFO:root:Starting finalizable transaction signer
INFO - Starting finalizable transaction signer
WARNING:root:app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
WARNING - app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
INFO:root:Stopping finalizable transaction signer
INFO - Stopping finalizable transaction signer
WARNING:root:app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
WARNING - app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
INFO:root:Preparing certificate batch
INFO - Preparing certificate batch
INFO:root:Issuing the certificates on the blockchain
INFO - Issuing the certificates on the blockchain
Traceback (most recent call last):
  File "/usr/bin/cert-issuer", line 11, in <module>
    load_entry_point('cert-issuer==0.0.7', 'console_scripts', 'cert-issuer')()
  File "/usr/lib/python3.5/site-packages/cert_issuer/__main__.py", line 17, in cert_issuer_main
    issue_certificates.main(parsed_config)
  File "/usr/lib/python3.5/site-packages/cert_issuer/issue_certificates.py", line 67, in main
    tx_id = issuer.issue_certificates()
  File "/usr/lib/python3.5/site-packages/cert_issuer/issuer.py", line 114, in issue_certificates
    tx_id = self.issue_on_blockchain()
  File "/usr/lib/python3.5/site-packages/cert_issuer/issuer.py", line 43, in issue_on_blockchain
    op_return_value_bytes = unhexlify(self.tree.get_merkle_root())
  File "/usr/lib/python3.5/site-packages/cert_issuer/helpers.py", line 17, in unhexlify
    def unhexlify(hex_string): return binascii.unhexlify(hex_string.encode('utf8'))
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by kimdhamilton** [comment]
There are 2 separate issues:

- it looks like you didn't follow the README steps. The quickest way to start is to follow the [Quick start with Docker steps](https://github.com/blockchain-certificates/cert-issuer/blob/master/README.md)
- The script should detect if there are no certificates and return early. Checked in fix with [this commit](https://github.com/blockchain-certificates/cert-issuer/commit/1d36cb44f153c6f771288d1051c61ddf2155edaf)

**Comment by shivam3192** [comment]
Ma'm i have followed each and every step in the readme.md , and i have mentioned to you regarding the step in which i faced the problem 
and regarding your 2nd point can u please elaborate more because i could not unserstand what u are trying to say

**Comment by kimdhamilton** [comment]
I think I see the problem -- did you run this step in the README?
```
1. Add your certificate to /etc/cert-issuer/data/unsigned_certificates/. 
```

I just submitted an update to the docs to give the precise command in the docker container (before it asked you to derive the path). Try running this before issuing:

    ```
    cp /cert-issuer/examples/data-testnet/unsigned_certificates/6c6bd2ec-d0d6-41a9-bec8-57bb904c62a8.json /etc/cert-issuer/data/unsigned_certificates/ 
    
    ```
