### ISSUE TITLE
Cert-Issuer through MainNet

### ISSUE THREAD

**Issue by deependersingla** [blockchain-certificates/cert-issuer#46]
Hello,

First off, thanks for the great work on the project. I started integrating with the system a week back and till now it has worked like charm. 
I have few question before using it on mainnet:

a) For issuing on mainNet, [link](https://github.com/blockchain-certificates/cert-issuer/blob/master/docs/bitcoin_options.md) suggested method is to use USB. Any way I can overwrite this? What if I give a path to a cert-issuer directory like in regtest, will it still work? 

b) Is the instruction given [here]((https://github.com/blockchain-certificates/cert-issuer/blob/master/docs/bitcoin_options.md) are latest? Asking this because first advanced docs link (Overview of issuing options) from Readme returns 404. 

c) Can I just update docker generated conf.ini at /etc/cert-issuer/work to have mainnet as bitcoin_chain and other accounts id accordingly. Will it then make a transaction on mainnet? Because this [doc ](https://github.com/blockchain-certificates/cert-issuer/blob/master/docs/issuing.md) suggest `python cert-issuer -c conf.ini` if i have installed package. which method is more recommended docker or package installation?

Please let me know if this is not a right place to ask above question. I will delete it and post it where you will recommend.

Best,
Deep

**Comment by kimdhamilton** [comment]
Hi Deep,
I'm sorry for the delay. Responses below:

a. It will still work if you give a local path. If you're going this route, it would be preferable to create an encrypted SecureSigner subclass (or at least minimize the exposure of your private key in a similar manner). This is the main concern to be aware of.
b. Apologies! I updated the link
c. If you want to run a full bitcoin node, it's better to run outside of docker, but there are easier options as well. By default, in both testnet and mainnet, cert-issuer will use broadcasting APIs, which allow you to avoid running a bitcoin node. 

You still have to generate the bitcoin address (you can use [this client-side generator](https://www.bitaddress.org/bitaddress.org-v3.3.0-SHA256-dec17c07685e1870960903d8f58090475b25af946fe95a734f88408cef4aa194.html)) and obtain some coins. Obtaining mainnet coins is still the most tedious part -- basically you need to acquire them, and then transfer to the address you created. While you are waiting for this process, you can also try testnet issuing; you can use a testnet faucet to get some for free.

Let me know if you have any other questions. 

Thanks, Kim

**Comment by deependersingla** [comment]
Hello Kim,

Thanks a lot for the reply. It helped a lot. For our application:
I am generating an unsigned certificate using Accredible infra (I am a developer with Accredible) and then using cert-issuer I am making a blockchain transaction. I have updated Accredible generating certs schema to match with block cert schema. It works great on both testnet and rigtest under docker installation. 

The only thing left before moving on to mainnet is to use cert-issuer as python package and then run a command like `python cert-issuer -c conf.ini` rather than using docker installation. But I was never able to successfully install cert-issuer as pip package. Some of the question I have is:
a) Should I continue using docker and write some hack in between to make this work automatically.?
b) Any other way to use cert-issuer without docker?
c) Anything I am missing while installing cert-issuer package?

The latest error I get is this: 
`InstallationError: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pysha3/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Ad7PLP-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pysha3`

Best,
Deep

**Comment by kimdhamilton** [comment]
Hi Deep,
That's great to hear that you and Accredible are using our project! I think my previous answer was a bit ambiguous on some points, so let me start again. You can perform testnet/mainnet issuing docker, but note that the Dockerfile is configured to run the bitcoin node in regtest mode. So if you are running cert-issuer in docker in testnet or mainnet mode, it essentially ignores the bitcoin node in the container, and instead uses bitcoin apis. 

Stated differently, the Dockerfile is largely provided to make the regtest path easiest, since it does not write to a ledger and is easiest for testing (but hardest for setup, because it requires the bitcoin node). This means that for mainnet and testnet, the bitcoin process in the docker container is useless, but harmless.

Because cert-issuer in mainnet and testnet modes can run exclusively with bitcoin apis (i.e. no need for a bitcoin node), you can (in theory) just as easily use it outside of docker. However, as you're experiencing, some system dependencies are missing.

Note the first `RUN` line in Dockerfile:
```
apk add --update bash python3 python3-dev ca-certificates linux-headers gcc musl-dev 
```

I'm not sure which OS you are running (Ubuntu?), so the names may vary for your package manager.

I will update the instructions to clarify this as well. Please let me know if you have any other issues getting mainnet issuing to work. 

Best,
Kim

**Comment by kimdhamilton** [comment]
Hi Deep,
Can you try directly running issuer_certificates.py? 
```
python <project_home>/cert-issuer/cert_issuer/issue_certificates.py -c <path_to_conf.ini>
```

**Comment by kimdhamilton** [comment]
Hi Deep,
I'm closing this for now. Let me know if you still have any issues. Also, you're interested, we have a community forum at http://community.blockcerts.org. It would be great to see you there.
Thanks,
Kim

**Comment by deependersingla** [comment]
Hello Kim,

Apology for the delay in response. I just tried it and it worked. Thanks a lot for your help. Yes, I will join the community.

Kind Regards,
Deep

**Comment by deependersingla** [comment]
Hello Kim,

Apology for opening this issue again. I was just setting up everything without docker. I get this error:
`ERROR:root:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "/home/ubuntu/development/cert-issuer/cert_issuer/issue_certificates.py", line 92, in <module>
    tx_id = main(parsed_config, secret_manager)
  File "/home/ubuntu/development/cert-issuer/cert_issuer/issue_certificates.py", line 72, in main
    tx_id = issuer.issue_certificates()
  File "/usr/local/lib/python3.4/dist-packages/cert_issuer/issuer.py", line 132, in issue_certificates
    tx_id = self.issue_on_blockchain()
  File "/usr/local/lib/python3.4/dist-packages/cert_issuer/issuer.py", line 46, in issue_on_blockchain
    op_return_value_bytes = unhexlify(self.tree.get_merkle_root())
  File "/usr/local/lib/python3.4/dist-packages/cert_issuer/helpers.py", line 17, in unhexlify
    def unhexlify(hex_string): return binascii.unhexlify(hex_string.encode('utf8'))
AttributeError: 'bytes' object has no attribute 'encode'
ERROR - 'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "/home/ubuntu/development/cert-issuer/cert_issuer/issue_certificates.py", line 92, in <module>
    tx_id = main(parsed_config, secret_manager)
  File "/home/ubuntu/development/cert-issuer/cert_issuer/issue_certificates.py", line 72, in main
    tx_id = issuer.issue_certificates()
  File "/usr/local/lib/python3.4/dist-packages/cert_issuer/issuer.py", line 132, in issue_certificates
    tx_id = self.issue_on_blockchain()
  File "/usr/local/lib/python3.4/dist-packages/cert_issuer/issuer.py", line 46, in issue_on_blockchain
    op_return_value_bytes = unhexlify(self.tree.get_merkle_root())
  File "/usr/local/lib/python3.4/dist-packages/cert_issuer/helpers.py", line 17, in unhexlify
    def unhexlify(hex_string): return binascii.unhexlify(hex_string.encode('utf8'))
AttributeError: 'bytes' object has no attribute 'encode'
 => "" 
`
I am calling the command from ruby application. As other stack in that, using command:
<sudo python3 /home/ubuntu/development/cert-issuer/cert_issuer/issue_certificates.py -c /home/ubuntu/development/ruby_blockchain_middleware/conf_updated.ini>

Now conf_updated.ini looks like this:
`issuing_address = random_address
revocation_address = random_address2

bitcoin_chain=testnet

usb_name=/home/ubuntu/development/ruby_blockchain_middleware/
key_file=pk_issuer.txt

unsigned_certificates_dir=/home/ubuntu/development/ruby_blockchain_middleware/unsigned
signed_certificates_dir=/home/ubuntu/development/ruby_blockchain_middleware/signed
blockchain_certificates_dir=/home/ubuntu/development/ruby_blockchain_middleware/blockchain
work_dir=/home/ubuntu/development/ruby_blockchain_middleware/work

no_safe_mode`

pk_issuer.txt
`random_key2`

cert json:
https://s3.amazonaws.com/staging-accredible-blockchain/unsigned/10299954.json

When I use the same conf.ini file address and cert JSON inside docker app. It works fine. So the address is correct and cert JSON also. 

Any idea, what I can do to debug this?
