### ISSUE TITLE
cert-issuing fails without docker

### ISSUE THREAD

**Issue by deependersingla** [blockchain-certificates/cert-issuer#49]
Hello Kim,

Apology for opening a new issue. Let me know if I should add this to [old thread](https://github.com/blockchain-certificates/cert-issuer/issues/46)?

I was just setting up everything without docker. I get this error:

> ERROR:root:'bytes' object has no attribute 'encode'
> Traceback (most recent call last):
> File "/home/ubuntu/development/cert-issuer/cert_issuer/issue_certificates.py", line 92, in 
> tx_id = main(parsed_config, secret_manager)
> File "/home/ubuntu/development/cert-issuer/cert_issuer/issue_certificates.py", line 72, in main
> tx_id = issuer.issue_certificates()
> File "/usr/local/lib/python3.4/dist-packages/cert_issuer/issuer.py", line 132, in issue_certificates
> tx_id = self.issue_on_blockchain()
> File "/usr/local/lib/python3.4/dist-packages/cert_issuer/issuer.py", line 46, in issue_on_blockchain
> op_return_value_bytes = unhexlify(self.tree.get_merkle_root())
> File "/usr/local/lib/python3.4/dist-packages/cert_issuer/helpers.py", line 17, in unhexlify
> def unhexlify(hex_string): return binascii.unhexlify(hex_string.encode('utf8'))
> AttributeError: 'bytes' object has no attribute 'encode'
> ERROR - 'bytes' object has no attribute 'encode'
> Traceback (most recent call last):
> File "/home/ubuntu/development/cert-issuer/cert_issuer/issue_certificates.py", line 92, in 
> tx_id = main(parsed_config, secret_manager)
> File "/home/ubuntu/development/cert-issuer/cert_issuer/issue_certificates.py", line 72, in main
> tx_id = issuer.issue_certificates()
> File "/usr/local/lib/python3.4/dist-packages/cert_issuer/issuer.py", line 132, in issue_certificates
> tx_id = self.issue_on_blockchain()
> File "/usr/local/lib/python3.4/dist-packages/cert_issuer/issuer.py", line 46, in issue_on_blockchain
> op_return_value_bytes = unhexlify(self.tree.get_merkle_root())
> File "/usr/local/lib/python3.4/dist-packages/cert_issuer/helpers.py", line 17, in unhexlify
> def unhexlify(hex_string): return binascii.unhexlify(hex_string.encode('utf8'))
> AttributeError: 'bytes' object has no attribute 'encode'
> => ""

I am calling the below command from ruby application.
`sudo python3 /home/ubuntu/development/cert-issuer/cert_issuer/issue_certificates.py -c /home/ubuntu/development/ruby_blockchain_middleware/conf_updated.ini`

I am on the latest master. Now conf_updated.ini looks like this:

```
issuing_address = random_address
revocation_address = random_address2

bitcoin_chain=testnet

usb_name=/home/ubuntu/development/ruby_blockchain_middleware/
key_file=pk_issuer.txt

unsigned_certificates_dir=/home/ubuntu/development/ruby_blockchain_middleware/unsigned
signed_certificates_dir=/home/ubuntu/development/ruby_blockchain_middleware/signed
blockchain_certificates_dir=/home/ubuntu/development/ruby_blockchain_middleware/blockchain
work_dir=/home/ubuntu/development/ruby_blockchain_middleware/work

no_safe_mode
```
pk_issuer.txt
`random_key2`

cert json:
https://s3.amazonaws.com/staging-accredible-blockchain/unsigned/10299954.json

When I use the same conf.ini file address and cert JSON inside docker app. It works fine. So the address is correct and cert JSON also.

Any idea, what I can do to debug this?

**Comment by kimdhamilton** [comment]
I just tried issuing and it worked for me. This part of the stack trace looked suspicious (a string is expected but bytes were received). I wonder if some of the python dependencies are in an inconsistent state?

```
op_return_value_bytes = unhexlify(self.tree.get_merkle_root())
File "/usr/local/lib/python3.4/dist-packages/cert_issuer/helpers.py", line 17, in unhexlify
def unhexlify(hex_string): return binascii.unhexlify(hex_string.encode('utf8'))
AttributeError: 'bytes' object has no attribute 'encode'
```

Note that, to make sure my environment is clean, I always test with a new python virtualenv so I know all the dependencies are updated and consistent.

**Comment by kimdhamilton** [comment]
I'm sending you the issued certificate

**Comment by deependersingla** [comment]
Thanks again, I will update dependency and will start using virtualenv. You can close the issue.
