### ISSUE TITLE
Merkle tree in version 2

### ISSUE THREAD

**Issue by BardoBravo** [blockchain-certificates/cert-issuer#55]
Hello,
By reading the MIT blog in [https://medium.com/mit-media-lab/what-we-learned-from-designing-an-academic-certificates-system-on-the-blockchain-34ba5874f196](url), you mention that in version 2 you would use a Merkle for storage of certificates.
Since this tree would be a single transaction in the blockchain, how do you proceed when the user wants to add a new certificate? A new node is created with the existing node content plus the new data? How is the old node exluded from further validations?
Regards,
Cláudio Ramos

**Comment by kimdhamilton** [comment]
Hi Cláudio,
In the current implementation, issuances are done 1 batch at a time, and certificates are revoked through the Open Badge `revocationList` scheme (at the moment, issuer hosted URI). To issue new certificates, the issuer would create a new batch, but doesn't have to re-issue previous batches.

Batches are best used as a natural grouping of certificates and recipients, i.e. participants in an online class who have completed their coursework, for reducing issuance cost. But it doesn't have any other significance. I.e. if the issuer inadvertently omitted a recipient and later wanted to issue to that recipient, the issuer can leave the previous batch in tact and simply issue a new batch.

Different implementations of Blockcerts in the future may handle this differently; i.e. a smart contract implementation may allow updating set membership. Similarly, different implementations of Blockcerts will very likely implement revocation differently.

Thanks,
Kim

**Comment by BardoBravo** [comment]
Hi @kimdhamilton,
Thanks for the info.
So in the end you set the older batch (transaction) as part of a revocationList, and add a new transaction (batch) with the new certificate, including the previous existing ones.
In this context, entering a data into revocationList is also an transaction done in the blockchain? And whenever a check is done over a certificate validity this revocationList is verified?
Hugs,
Cláudio

**Comment by kimdhamilton** [comment]
Hi Cláudio,
I'm sorry for the delay! Note that you don't necessarily need to re-issue the certificates from the original batch -- they will continue to validate even if a new batch is issued.

Currently, revocation is done per the OB standard (revocation list is available at an issuer URL), but we are actively investigating other implementations that are blockchain-backed.

Best,
Kim
