### ISSUE TITLE
Cert-issuer when Issuing certificate

### ISSUE THREAD

**Issue by lakshayghai** [blockchain-certificates/cert-issuer#61]
I am running the commands step by step as mentioned in the Readme. I am facing this exception.
Stack trace below

bash-4.3# cert-issuer -c /etc/cert-issuer/conf.ini
WARNING:root:Your app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
INFO:root:Set cost constants to recommended_tx_fee=0.000600,min_per_output=0.000028,satoshi_per_byte=250
INFO - Set cost constants to recommended_tx_fee=0.000600,min_per_output=0.000028,satoshi_per_byte=250
INFO:root:Processing 1 certificates
INFO - Processing 1 certificates
INFO:root:Processing 1 certificates under work path=/etc/cert-issuer/work
INFO - Processing 1 certificates under work path=/etc/cert-issuer/work
INFO:root:Total cost will be 133500 satoshis
INFO - Total cost will be 133500 satoshis
INFO:root:Starting finalizable signer
INFO - Starting finalizable signer
WARNING:root:app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
WARNING - app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
INFO:root:Stopping finalizable signer
INFO - Stopping finalizable signer
WARNING:root:app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
WARNING - app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
INFO:root:Unsigned hextx=01000000019340a205781240a858d6f9f4d0fdd481e7a2974d4d7a3d09f3eb38d64c7313f40100000000ffffffff02a07acc1d000000001976a9142af2b6b8244f5d26f3f9450540c27eb4cacba37888ac0000000000000000226a20819c418583a11b0d4351a96aba97534db2c758f655220d76a1ad984cf13b10d900000000
INFO - Unsigned hextx=01000000019340a205781240a858d6f9f4d0fdd481e7a2974d4d7a3d09f3eb38d64c7313f40100000000ffffffff02a07acc1d000000001976a9142af2b6b8244f5d26f3f9450540c27eb4cacba37888ac0000000000000000226a20819c418583a11b0d4351a96aba97534db2c758f655220d76a1ad984cf13b10d900000000
INFO:root:Preparing tx for signing
INFO - Preparing tx for signing
INFO:root:Starting finalizable signer
INFO - Starting finalizable signer
WARNING:root:app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
WARNING - app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
ERROR:root:Unable to sign transaction. hextx=01000000019340a205781240a858d6f9f4d0fdd481e7a2974d4d7a3d09f3eb38d64c7313f40100000000ffffffff02a07acc1d000000001976a9142af2b6b8244f5d26f3f9450540c27eb4cacba37888ac0000000000000000226a20819c418583a11b0d4351a96aba97534db2c758f655220d76a1ad984cf13b10d900000000
ERROR - Unable to sign transaction. hextx=01000000019340a205781240a858d6f9f4d0fdd481e7a2974d4d7a3d09f3eb38d64c7313f40100000000ffffffff02a07acc1d000000001976a9142af2b6b8244f5d26f3f9450540c27eb4cacba37888ac0000000000000000226a20819c418583a11b0d4351a96aba97534db2c758f655220d76a1ad984cf13b10d900000000
INFO:root:Stopping finalizable signer
INFO - Stopping finalizable signer
WARNING:root:app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
WARNING - app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
Traceback (most recent call last):
  File "/usr/bin/cert-issuer", line 11, in <module>
    load_entry_point('cert-issuer==2.0.8', 'console_scripts', 'cert-issuer')()
  File "/usr/lib/python3.5/site-packages/cert_issuer/__main__.py", line 17, in cert_issuer_main
    issue_certificates.main(parsed_config)
  File "/usr/lib/python3.5/site-packages/cert_issuer/issue_certificates.py", line 56, in main
    return issue(app_config, certificate_batch_handler, transaction_handler)
  File "/usr/lib/python3.5/site-packages/cert_issuer/issue_certificates.py", line 39, in issue
    tx_id = issuer.issue()
  File "/usr/lib/python3.5/site-packages/cert_issuer/issuer.py", line 27, in issue
    txid = self.transaction_handler.issue_transaction(op_return_bytes)
  File "/usr/lib/python3.5/site-packages/cert_issuer/transaction_handler.py", line 82, in issue_transaction
    signed_tx = self.sign_transaction(prepared_tx)
  File "/usr/lib/python3.5/site-packages/cert_issuer/transaction_handler.py", line 118, in sign_transaction
    signed_tx = signer.sign_transaction(prepared_tx)
  File "/usr/lib/python3.5/site-packages/cert_issuer/signer.py", line 120, in sign_transaction
    return self.signer.sign_transaction(self.wif, transaction_to_sign)
  File "/usr/lib/python3.5/site-packages/cert_issuer/signer.py", line 99, in sign_transaction
    raise UnableToSignTxError('Unable to sign transaction')
cert_issuer.errors.UnableToSignTxError: Unable to sign transaction

Please let me know whats the issue

**Comment by kimdhamilton** [comment]
I'm assuming you are using the docker "quick start" instructions? This looks like a problem caused by a stale docker image. I clean up my docker images and containers every now and then by running the following (you may need to adapt it, depending on your installation):

```
docker rm -v $(docker ps -a -q -f status=exited)

docker run -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm martin/docker-cleanup-volumes
```

**Comment by lakshayghai** [comment]
Thanks.
Issue Resolved

**Comment by pwjack** [comment]
> Thanks.
> Issue Resolved

How can I solve this problem? I have the same problem.
