### ISSUE TITLE
Support Decentralized identifiers

### ISSUE THREAD

**Issue by kimdhamilton** [blockchain-certificates/cert-issuer#69]
_From @kimdhamilton on September 27, 2017 20:5_

Instead of relying on public keys, we want to use Decentralized Identifiers (DIDs), since these enable longer-lived Blockcert ownership.

Note that the [decentralized identifier spec](https://w3c-ccg.github.io/did-spec/) is still being finalized in the W3C Credentials CG. There are 2 known (at this time) mostly compliant (i.e. the spec still isn't finalized) method specs -- Veres 1 and BTCR. Other popular method specs such as Sovrin and uPort are expected to comply shortly after spec finalization.

Blockcerts won't tie to any specific DID provider. Rather it only knows about DIDs. We may, for purposes of prototypes, show examples with the simplest DID method, i.e. [BTCR](https://weboftrustinfo.github.io/btcr-tx-playground.github.io/).

DIDs enable more user-friendly means of recovery, e.g. social recovery in the case that you lose your device, or in some way make your private keys unrecoverable.

The schema change is super simple: we will simply use Verifiable Claims conventions enabling `id`, `entity`, and `owner` to be DIDs.

Changes to the Blockcerts ecosystem could be interesting:
- wallet could understand and integrate with DID providers
- if the DID provider supports service-based DID verification, the Blockcerts verifier could incorporate this notion
 
In general, this nicely decouples Blockcerts from key management.

_Copied from original issue: blockchain-certificates/cert-schema#41_

**Comment by lemoustachiste** [comment]
Supported
