### ISSUE TITLE
Blockcerts as Verifiable Claims

### ISSUE THREAD

**Issue by kimdhamilton** [blockchain-certificates/cert-issuer#70]
_From @kimdhamilton on September 27, 2017 19:35_

We want to use the Verifiable Claims schema, but in an Open Badges compatible way; ideally by "integrating" Open Badges with Verifiable Claims directly

_Copied from original issue: blockchain-certificates/cert-schema#39_

**Comment by kimdhamilton** [comment]
https://hackmd.io/KSb2xvZFR2ORapRqeq68Rw

**Comment by lemoustachiste** [comment]
VC is implemented, Open Badges V3 to align with VC, I believe merging the 2 at this point should be straightforward (a matter of putting the right contexts in place).
