### ISSUE TITLE
Getting error when I created certificates using testnet address.

### ISSUE THREAD

**Issue by Prabhat-Sutar** [blockchain-certificates/cert-issuer#73]
Getting this error: Not a valid certificate. Transaction occurred at time when issuing address was not considered valid.

**Comment by kimdhamilton** [comment]
Hi @Prabhat-Emorphis, 
This error happens if you don't have a valid, hosted issuer.json file, which you can create with cert-tools. This is the url in the `issuer.id` field. If you've done that, be sure to check the dates of the issuing address on that issuer.json file.
Thanks,
Kim

**Comment by kimdhamilton** [comment]
Here is a reference you may find useful: http://community.blockcerts.org/t/issuer-hosting-requirements/31
