### ISSUE TITLE
Error - Permission denied

### ISSUE THREAD

**Issue by Judebrian** [blockchain-certificates/cert-issuer#77]
i am facing this issue where it keeps stating permission denied.

(venv) brendanluke_sf@quest-cert:~/venv/cert-issuer$ python issue_certificates.py -c config.ini
WARNING - Your app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
INFO - This run will try to issue on the bitcoin_testnet chain
INFO - Set cost constants to recommended_tx_fee=0.000600,min_per_output=0.000028,satoshi_per_byte=250
INFO - Set cost constants to recommended_tx_fee=0.000600,min_per_output=0.000028,satoshi_per_byte=250
ERROR - [Errno 13] Permission denied: '/etc/cert-issuer'
Traceback (most recent call last):
  File "issue_certificates.py", line 60, in <module>
    tx_id = main(parsed_config)
  File "issue_certificates.py", line 52, in main
    return issue(app_config, certificate_batch_handler, transaction_handler)
  File "issue_certificates.py", line 21, in issue
    blockchain_certificates_dir, work_dir)
  File "/home/brendanluke_sf/venv/cert-issuer/cert_issuer/helpers.py", line 45, in prepare_issuance_batch
    os.makedirs(work_dir, exist_ok=True)
  File "/home/brendanluke_sf/venv/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/brendanluke_sf/venv/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/etc/cert-issuer'
ERROR - [Errno 13] Permission denied: '/etc/cert-issuer'
Traceback (most recent call last):
  File "issue_certificates.py", line 60, in <module>
    tx_id = main(parsed_config)
  File "issue_certificates.py", line 52, in main
    return issue(app_config, certificate_batch_handler, transaction_handler)
  File "issue_certificates.py", line 21, in issue
  File "/home/brendanluke_sf/venv/cert-issuer/cert_issuer/helpers.py", line 45, in prepare_issuance_batch
    blockchain_certificates_dir, work_dir)
  File "/home/brendanluke_sf/venv/cert-issuer/cert_issuer/helpers.py", line 45, in prepare_issuance_batch
    os.makedirs(work_dir, exist_ok=True)
  File "/home/brendanluke_sf/venv/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/brendanluke_sf/venv/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/etc/cert-issuer'
(venv) brendanluke_sf@quest-cert:~/venv/cert-issuer$

I dont have such a folder called etc....
Can someone please help me.

**Comment by kimdhamilton** [comment]
Hi @Judebrian, 
You can simply override the paths in the conf.ini file to whichever path you want.
Thanks,
Kim

**Comment by Judebrian** [comment]
Thank you so much.
I have got the issuer working.
If you don't ming me asking.
How do I create my own certificates using the similar template as the
sample certificates.
I have cloned the cert schema, but I'm unsure on which template should I
take to modify.
Thank you.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kimdhamilton** [comment]
Hi @Judebrian, the cert-tools tool lets you do that. It has a README that should help with the process.
Thanks,
Kim

**Comment by Judebrian** [comment]
Thank you Kim.
If you don't mind me asking, using mainnet how do I issue the certificates
on an actual website instead of a flask server.
Because currently it is only running on my localhost.

Thank you.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Judebrian** [comment]
Dear Miss Kim,
Good afternoon.
How much would it cost exactly in satoshis to issue a batch of certificates.
Thank you.
