### ISSUE TITLE
Insufficient Funds Error

### ISSUE THREAD

**Issue by itinawi** [blockchain-certificates/cert-issuer#80]
I am getting the following error when I try to issue certificates either in bitcoin testnet or using docker and regtest. My bitcoin testnet wallet has 3.5 btcs and for the docker app, I am just following the steps in cert-issuer for the bitcoin-cli. Could you please post more detailed steps on how to make sure there are sufficient funds for both?

Thanks!

Error: 

WARNING - Your app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
INFO - This run will try to issue on the bitcoin_regtest chain
INFO - Set cost constants to recommended_tx_fee=0.000600,min_per_output=0.000028,satoshi_per_byte=250
INFO - Set cost constants to recommended_tx_fee=0.000600,min_per_output=0.000028,satoshi_per_byte=250
INFO - Processing 2 certificates
INFO - Processing 2 certificates
INFO - Processing 2 certificates under work path=/Users/itinawi/superurop/cert-issuer/data/work
INFO - Processing 2 certificates under work path=/Users/itinawi/superurop/cert-issuer/data/work
WARNING - [Errno 2] No such file or directory: '/Users/itinawi/Library/Application Support/Bitcoin/bitcoin.conf'
WARNING - [Errno 2] No such file or directory: '/Users/itinawi/Library/Application Support/Bitcoin/bitcoin.conf'
WARNING - address mt8vRAdRifBTrCsA4Ja1SK2DwNLknbsqVZ has a balance of 0
WARNING - address mt8vRAdRifBTrCsA4Ja1SK2DwNLknbsqVZ has a balance of 0
INFO - Total cost will be 133500 satoshis
INFO - Total cost will be 133500 satoshis
ERROR - Please add 133500 satoshis to the address mt8vRAdRifBTrCsA4Ja1SK2DwNLknbsqVZ
ERROR - Please add 133500 satoshis to the address mt8vRAdRifBTrCsA4Ja1SK2DwNLknbsqVZ
Traceback (most recent call last):
  File "/Users/itinawi/superurop/cert-issuer/venv/bin/cert-issuer", line 11, in <module>
    load_entry_point('cert-issuer==2.0.11', 'console_scripts', 'cert-issuer')()
  File "/Users/itinawi/superurop/cert-issuer/venv/lib/python3.6/site-packages/cert_issuer-2.0.11-py3.6.egg/cert_issuer/__main__.py", line 17, in cert_issuer_main
    issue_certificates.main(parsed_config)
  File "/Users/itinawi/superurop/cert-issuer/venv/lib/python3.6/site-packages/cert_issuer-2.0.11-py3.6.egg/cert_issuer/issue_certificates.py", line 52, in main
    return issue(app_config, certificate_batch_handler, transaction_handler)
  File "/Users/itinawi/superurop/cert-issuer/venv/lib/python3.6/site-packages/cert_issuer-2.0.11-py3.6.egg/cert_issuer/issue_certificates.py", line 30, in issue
    transaction_handler.ensure_balance()
  File "/Users/itinawi/superurop/cert-issuer/venv/lib/python3.6/site-packages/cert_issuer-2.0.11-py3.6.egg/cert_issuer/bitcoin/transaction_handlers.py", line 51, in ensure_balance
    raise InsufficientFundsError(error_message)
cert_issuer.errors.InsufficientFundsError: Please add 133500 satoshis to the address mt8vRAdRifBTrCsA4Ja1SK2DwNLknbsqVZ

**Comment by itinawi** [comment]
Ok so I realized that perhaps why this isn't working locally is that I didn't follow the steps needed to set up my own local bitcoin node. (please consider moving this information up, since I only saw it when I scrolled all the way down: https://github.com/blockchain-certificates/cert-issuer/blob/master/docs/bitcoind.md)

Anyway, I'd still like to go through the workflow of issuing my own certificates, and I guess the way forward is to use bitcoin testnet. I am hosting my own issuer-testnet.json file here and have updated it with my bitcoin testnet public key. I also have the issuer-testnet.json file in the cert-issuer directory.
Link:
https://github.com/itinawi/blockcerts_urop/blob/master/testnet_stuff/issuer-testnet.json

**Comment by itinawi** [comment]
To be more specific, this is the error I get for testnet issuing:

WARNING - Your app is configured to skip the wifi check when the USB is plugged in. Read the documentation to ensure this is what you want, since this is less secure
INFO - This run will try to issue on the bitcoin_testnet chain
INFO - Set cost constants to recommended_tx_fee=0.000600,min_per_output=0.000028,satoshi_per_byte=250
INFO - Set cost constants to recommended_tx_fee=0.000600,min_per_output=0.000028,satoshi_per_byte=250
INFO - Processing 2 certificates
INFO - Processing 2 certificates
INFO - Processing 2 certificates under work path=/Users/itinawi/superurop/cert-issuer/data/work
INFO - Processing 2 certificates under work path=/Users/itinawi/superurop/cert-issuer/data/work
WARNING - <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>
WARNING - <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>
WARNING - address mzkqackHtDiCR2sRPMxNtKYWm9cA4WaXaH has a balance of 0
WARNING - address mzkqackHtDiCR2sRPMxNtKYWm9cA4WaXaH has a balance of 0
INFO - Total cost will be 133500 satoshis
INFO - Total cost will be 133500 satoshis
ERROR - Please add 133500 satoshis to the address mzkqackHtDiCR2sRPMxNtKYWm9cA4WaXaH
ERROR - Please add 133500 satoshis to the address mzkqackHtDiCR2sRPMxNtKYWm9cA4WaXaH
Traceback (most recent call last):
  File "/Users/itinawi/superurop/cert-issuer/venv3/bin/cert-issuer", line 11, in <module>
    load_entry_point('cert-issuer==2.0.11', 'console_scripts', 'cert-issuer')()
  File "/Users/itinawi/superurop/cert-issuer/venv3/lib/python3.6/site-packages/cert_issuer-2.0.11-py3.6.egg/cert_issuer/__main__.py", line 17, in cert_issuer_main
    issue_certificates.main(parsed_config)
  File "/Users/itinawi/superurop/cert-issuer/venv3/lib/python3.6/site-packages/cert_issuer-2.0.11-py3.6.egg/cert_issuer/issue_certificates.py", line 52, in main
    return issue(app_config, certificate_batch_handler, transaction_handler)
  File "/Users/itinawi/superurop/cert-issuer/venv3/lib/python3.6/site-packages/cert_issuer-2.0.11-py3.6.egg/cert_issuer/issue_certificates.py", line 30, in issue
    transaction_handler.ensure_balance()
  File "/Users/itinawi/superurop/cert-issuer/venv3/lib/python3.6/site-packages/cert_issuer-2.0.11-py3.6.egg/cert_issuer/bitcoin/transaction_handlers.py", line 51, in ensure_balance
    raise InsufficientFundsError(error_message)
cert_issuer.errors.InsufficientFundsError: Please add 133500 satoshis to the address mzkqackHtDiCR2sRPMxNtKYWm9cA4WaXaH

**Comment by kimdhamilton** [comment]
Hi @itinawi,
There were some dependency issues that were fixed with https://github.com/blockchain-certificates/cert-issuer/commit/56d5655c18ae30ee8b17603b99580fc1fa427f08. I reran the docker build and steps described in the Quick Start, and confirmed this works. 

Thanks,
Kim

**Comment by Sphinxs** [comment]
Did you fix it @itinawi ?
